### ISSUE TITLE
data import

### ISSUE THREAD

**Issue by jiikl7777** [swsoyee/TCC-GUI#22]
Read count table 
还是觉得给看前几列没什么必要，如果只是看下数据有没有问题，那也没必要标红，前几列标红说明数值高也表现不出什么。

- [x] Group selection 
最好能识别除了123之外的分组信息吧

Sampl distribution
如果有几十个样本，这边是怎么处理的？自动变得每一条都很细应该也可以。

**Comment by swsoyee** [comment]
> Sample distribution
样本数多boxplot会自然压缩，可能问题就是Density plot的legend条目数量太多，会压缩图像导致看不清楚。待处理解决

> Group selection
分组信息更新下次更新

> read count table
暂时放着吧，现在貌似也没多影响
