### ISSUE TITLE
Online version not loading

### ISSUE THREAD

**Issue by kelseykeith** [swsoyee/TCC-GUI#39]
Hi!
When you try and load the online version (<https://infinityloop.shinyapps.io/TCC-GUI/>) there's a message saying "Please Wait", but it never loads. Is there an issue with the hosting?
Thanks!

**Comment by swsoyee** [comment]
@kelseykeith Thank you for your report! I have restarted the server, and it's seem to be work now. Maybe just an issue with shinyapps.io.

**Comment by kelseykeith** [comment]
Great, thank you!
