### ISSUE TITLE
wordのReport Generationのフリーズについて

### ISSUE THREAD

**Issue by qqsearch** [swsoyee/TCC-GUI#40]
**Describe the bug**
Report Generationでwordを選択した後に出力するとフリーズします。
また、htmlで出力した時に、volcano plotのtable出力ができていないような気がします。

確認をしていただけないでしょうか。よろしくお願い致します。

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Browser [chrome, Rからローカル起動]

**Comment by swsoyee** [comment]
返信遅くになってすみません。

>  Report Generationでwordを選択した後に出力するとフリーズします。

こちらではWordのフォーマットにも出力できますが、レポート機能自体の完成度は高くないためので、もし本当にレポートを出力したい場合HTMLをお勧めします。

> また、htmlで出力した時に、volcano plotのtable出力ができていないような気がします。

Volcano Plotのテーブルの出力機能は未実装です。お手数ですが、Volcano Plotのタブから結果テーブルをダウンロードしてください。

**Comment by hirotsuke** [comment]
２点承知しました。
