### ISSUE TITLE
heat mapで出力したTableでgene_idが表示されない

### ISSUE THREAD

**Issue by qqsearch** [swsoyee/TCC-GUI#41]
**Describe the bug**
heat mapで出力したTableでgene_idが表示されません。

Dclre1b-204
1810055G02Rik-202
Zbtb21-202
Man2c1-213

例えば、gene_idの表記がこのように４つある場合「1810055G02Rik-202」のみがTableに表示されます。残り３つのgene_idは、Tableで表示されませんでした。

よろしくお願いいたします。

**Comment by swsoyee** [comment]
ご報告ありがとうございます。修正致しました。
もし修正された内容はご報告した内容と一致しなければ再度確認しますので、Reopenしても構いません。

よろしくお願い致します。

**Comment by hirotsuke** [comment]
修正を確認致しました。
ご対応くださりありがとうございます。
