### ISSUE TITLE
Tableの拡張機能願い

### ISSUE THREAD

**Issue by qqsearch** [swsoyee/TCC-GUI#42]
テーブルデータをコピーアンドペーストで取ろうと思っていましたが、列の制限があるみたいです。（範囲選択中にスクロールすると数値が更新されてしまいます。

volcano plotのPDFの出力で約100列の出力となっておりますが、例えば500列ほどに出力できる拡張機能を搭載していただけないでしょうか。

どうぞよろしくお願い致します。

**Comment by swsoyee** [comment]
少し調査と開発の時間がかかりますが、対応致します。

**Comment by swsoyee** [comment]
@qqsearch お待たせしました。Volcano Plotの結果テーブルの下に一回で全てのデータをダウンロードできるボタンを追加しました。問題の解決ができたかどうかをお手数ですがご確認お願いいたします。

またバグや要望がありましたら随時コメントあるいはIssueを作ってください。
そうぞよろしくお願いいたします。

**Comment by qqsearch** [comment]
確認が遅くなりました。
Volcano Plotの結果テーブルは無事にDLできました。
とても助かります...!!
今後も利用させていただきます。ありがとうございました。
