### ISSUE TITLE
Disconnected from the Server

### ISSUE THREAD

**Issue by mWekking** [swsoyee/TCC-GUI#49]
I am tryining to run your pipeline on a custom dataset but once I get to the TCC it keeps disconnecting from the server?
I get a message "disconnected from the server reload"

This also happens with a smaller simulated dataset, what could be the problem?

**Comment by swsoyee** [comment]
Thanks for your reporting, I have restart and test the online version, it's seems that the speed of loading is very slow.
I have no idea why the loading of shinyapps.io speed is so slow now. It may be a temporary problem and you could try again later.
We are using the free version to host TCC-GUI (as a demo), and we are very sorry for the inconvenience but would you mind to install the local version for your analysis?

**Comment by mWekking** [comment]
Thanks for the quick response, I will run it locally!

**Comment by swsoyee** [comment]
It's seems that the server has been recovered. Would you might to have a test to make sure the app (demo) is working well?

**Comment by mWekking** [comment]
It sadly keeps disconnecting online... Trying it on about 550000 genes

**Comment by swsoyee** [comment]
On, I see, the free online version could not solve that size of dataset, so using the local version is the right approach!
I will consider adding a pop-up notification to inform the user.
