### ISSUE TITLE
inputファイルの低発現遺伝子のフィルタリングについて

### ISSUE THREAD

**Issue by qqsearch** [swsoyee/TCC-GUI#51]
お世話になっております。

素人質問になるのですが、インプットするTPMテーブルの数値０の遺伝子は、予め除去したほうが有意なDEG出力につながるのでしょうか。TPMは、salmonでの出力になります。

よろしくお願い致します。

**Comment by swsoyee** [comment]
いつもTCC-GUIのご利用をしてくださり、ありがとうございます。
Academic 問題に関しては、お手数ですが、下記のメールアドレスにご質問したほうがいいと思います。
koji.kadota(at)gmail.com

よろしくお願いいたします。

**Comment by qqsearch** [comment]
承知しました。メールで相談させていただきます。
ありがとうございます。
