### ISSUE TITLE
Could not restore the "renv"

### ISSUE THREAD

**Issue by domy1980** [swsoyee/TCC-GUI#53]
**Describe the bug**

I tried to restore "renv" but, the error code showed up and I could not proceed. I also tried to install "genefilter" with install packages("genefilter"), but even after that I could not restore with same error. I appreciate if you could help me to solve this problem. Thanks,

R was unable to find the gfortran binary.
gfortran is required for the compilation of FORTRAN source files.
Please check that gfortran is installed and available on the PATH.
Please see https://stackoverflow.com/q/35999874 for more information.

Reason(s):
- 'make: gfortran: No such file or directory'
 エラー: install of package 'genefilter' failed

**Comment by swsoyee** [comment]
As the message describe here, you need to install gfortran if you are using MAC.

https://stackoverflow.com/questions/35999874/mac-os-x-r-error-ld-warning-directory-not-found-for-option
https://stackoverflow.com/questions/23916219/os-x-package-installation-depends-on-gfortran-4-8

**Comment by domy1980** [comment]
Thank you!  installed gcc and checked the gfortran. Then I retried the installation of  TCC-GUI but, other error happened. install of package 'DESeq2' failed as below...

Could you tell me how to solve this...
I am using Mac (OS Catalina 10.15.7)

Thanks,



* installing to library ‘/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0’
* installing *source* package ‘DESeq2’ ...
** using staged installation
** libs
clang++ -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/Rcpp/include' -I'/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c DESeq2.cpp -o DESeq2.o
In file included from DESeq2.cpp:16:
In file included from /private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/RcppArmadilloForward.h:49:
In file included from /private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo:21:
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/compiler_check.hpp:50:4: error: "*** C++11 compiler required; enable C++11 mode in your compiler, or use an earlier version of Armadillo"
  #error "*** C++11 compiler required; enable C++11 mode in your compiler, or use an earlier version of Armadillo"
   ^
In file included from DESeq2.cpp:16:
In file included from /private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/RcppArmadillo.h:31:
In file included from /private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/RcppArmadilloForward.h:49:
In file included from /private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo:85:
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:149:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:150:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:151:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:161:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:162:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:163:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = true;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:173:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:174:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = true;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:175:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:185:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = true;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:186:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:187:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:197:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = T1::is_row;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:198:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = T1::is_col;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:199:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = T1::is_xvec;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:209:12: error: unknown type name 'constexpr'
    static constexpr bool is_row  = false;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:210:12: error: unknown type name 'constexpr'
    static constexpr bool is_col  = false;
           ^
/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/RcppArmadillo/include/armadillo_bits/arma_forward.hpp:211:12: error: unknown type name 'constexpr'
    static constexpr bool is_xvec = false;
           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [DESeq2.o] Error 1
ERROR: compilation failed for package ‘DESeq2’
* removing ‘/private/var/folders/rb/k3gksl7s5yjdct91b2g7dvj00000gn/T/RtmpzsjDrh/renv-staging-f73d10f27eb0/DESeq2’
 エラー: install of package 'DESeq2' failed

**Comment by swsoyee** [comment]
This issue has been solved and  duplicate to #54 , so I will close this one.
