### ISSUE TITLE
multi-group boxplots + comparisons

### ISSUE THREAD

**Issue by daaaaande** [swsoyee/TCC-GUI#57]
**Is your feature request related to a problem? Please describe.**
there are many rnaseq experiments with not only two groups - but 4 or even more

**Describe the solution you'd like**
stats with ANOVA/Tukey HSD values, multi- group boxplots, what-versus-what choices in many parts

**Describe alternatives you've considered**
-none-

**Additional context**
this is a high-level whishlist item that would require mayor reworks

**Comment by swsoyee** [comment]
Thanks for the feature request, the answer to this issue will be the same as https://github.com/swsoyee/TCC-GUI/issues/56#issuecomment-929339344 .
