### ISSUE TITLE
Cannot install packages with renv::restore

### ISSUE THREAD

**Issue by kokicoke** [swsoyee/TCC-GUI#61]
**Describe the bug**
When I try to install the nessesary packages using renv::restore, the installing does not work (stops at installing MASS), and I cannot proceed any further.

**To Reproduce**
I am following the steps for Method 1
1. cloned the files from Github and opened TCC-GUI.Rproj.
2. Execute renv::restore

3. Retreving files seems to be working?? but some packages are not initially downloaded.
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/MASS/MASS_7.3-58.3.tar.gz' ...
	OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/mgcv/mgcv_1.8-42.tar.gz' ...
	OK [file is up to date]
Retrieving 'https://cran.rstudio.com/src/contrib/Archive/nlme/nlme_3.1-162.tar.gz' ...
	OK [file is up to date]
Retrieving 'https://bioconductor.org/packages/3.16/bioc/bin/macosx/contrib/4.2/AnnotationDbi_1.60.2.tgz' ...
	OK [file is up to date]
Retrieving 'https://mran.microsoft.com/snapshot/2023-12-06/bin/macosx/contrib/4.2/DBI_1.1.3.tgz' ...
	ERROR [curl: (6) Could not resolve host: mran.microsoft.comcurl: (6) Could not resolve host: mran.microsoft.comcurl: (6) Could not resolve host: mran.microsoft.comcurl: (6) Could not resolve host: mran.microsoft.com]

4. Installing stops at MASS
Installing BiocManager [1.30.20] ...
	OK [linked cache in 0.16 milliseconds]
Installing renv [0.17.2] ...
	OK [linked cache in 0.14 milliseconds]
Installing codetools [0.2-19] ...
	OK [linked cache in 0.13 milliseconds]
Installing MASS [7.3-58.3] ...
	FAILED
Error installing package 'MASS':
================================

* installing *source* package ‘MASS’ ...
** package ‘MASS’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c MASS.c -o MASS.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c lqs.c -o lqs.o
clang -mmacosx-version-min=10.13 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o MASS.so MASS.o lqs.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: framework not found CoreFoundation
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Library/Frameworks/R.framework/Resources/share/make/shlib.mk:10: MASS.so] Error 1
ERROR: compilation failed for package ‘MASS’
* removing ‘/Users/koki/Desktop/TCC-GUI/renv/staging/1/MASS’
Error: install of package 'MASS' failed [error code 1]

**Expected behavior**
I wanted to install packages with renv::restore.

Based on looking up on the internet, maybe there is an issue with Xtools?

**Screenshots**
<img width="918" alt="スクリーンショット 2024-03-06 22 46 02" src="https://github.com/swsoyee/TCC-GUI/assets/43230297/0f94ab6d-cd70-4ba7-a92a-d539fe149564">

**Desktop (please complete the following information):**
 - Device: 14inch Macbook Pro 2021
 - CPU: Apple M1 Pro
 - OS: Mac OSX 14.3.1 Sonoma
 - R version: 4.2.2
 - RStudio Version: 2023.12.1+402 (2023.12.1+402)

**Comment by swsoyee** [comment]
Thank you for your report.
I have update those dependencies, please pull the latest code and try again.

If you still couldn't install it successfully, please try to install dependencies without `renv`.

```r
# Check "BiocManager"
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

# Package list
libs <- c("shiny", "shinydashboard", "shinyWidgets", "plotly", "dplyr", "DT", "heatmaply", "tidyr","utils","rmarkdown","data.table","RColorBrewer", "knitr", "cluster", "shinycssloaders", "shinyBS", "renv", "MASS", "TCC")

# Install packages if missing
for (i in libs){
  if( !is.element(i, .packages(all.available = TRUE)) ) {
     BiocManager::install(i, suppressUpdates=TRUE)
  }
}
```

**Comment by kokicoke** [comment]
Hi, before pulling the latest version I noticed that I hadn't updated my R ver to the latest, so I updated to 4.3.3.

renv::restore did not work, so I tried the code in your response.
 Initially it did not work, but I noticed that the error message asked for another package called "markdown" instead of "rmarkdown" so I added that into the list, installed that, and it seemed to work.

I have been trying for a while to install the desktop ver of TCC-GUI, and have finally got it to work with your help. 
Thank you very much for creating this tool, and providing wonderful support.

お忙しいところ大変お手数おかけいたしました。無事インストールできました。ありがとうございます。
